name: diabetes
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.24.3
  - pandas=2.0.3
  - scikit-learn=1.3.0
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - joblib=1.3.2
  - pip
  - pip:
    - streamlit==1.26.0
    - textblob==0.17.1
    - wordcloud==1.9.2
    - plotly==5.16.1
    